### ISSUE TITLE
Refactor: refactor directories of app router and some trivial codes according to inflearn lecture

### ISSUE THREAD

**Issue by Goonco** [swm-standard/phote-client#25]
### 🤔 Description

* 인프런 강의 및 Next.js 문서를 바탕으로 코드를 리팩토링한다. 가장 큰 포인트는 app router의 형태이다.

### 📌 ToDo

* **App Router**
  - [X] Next.js의 Parallel & Intercepting routing을 바탕으로 기존의 app directory 리팩토링
  - [X] Next.js의 Private folder & Route group을 바탕으로 기존의 app directory를 리팩토링
* **Others**
  - [X] `dvw`,`dvh` 활용

### 💬 Others

* 코드 깔끔해질 수록 마음이 편해진다 😌
