### ISSUE TITLE
Design: publishing workbook page

### ISSUE THREAD

**Issue by Goonco** [swm-standard/phote-client#30]
### 🤔 Description

* 문제집 조회 페이지에 대한 퍼블리싱을 진행한다.
* 진행 과정에서 tailwind와 관련된 세팅 및 layout과 component 구성의 수정이 발생할 수 있으나 기존의 로직은 최대한 수정하지 않고 퍼블리싱을 진행한다.

### 📌 ToDo

- [X] tailwindCss에 custom color 추가
- [X] pretendard font 추가
- [X] 배너를 포함한 문제집 조회 페이지 퍼블리싱

### 💬 Others

* 문제 생성 페이지 어려워서 퍼블리싱으로 도망온건 안비밀 🤐
