### ISSUE TITLE
Refactor: refactor workbook page layout and navigation component

### ISSUE THREAD

**Issue by Goonco** [swm-standard/phote-client#32]
### 🤔 Description

* 기존 문제집 화면의 `flex-grow` 와 관련된 CSS 로직을 보다 가시화 할 수 있도록 리팩토링을 진행한다.
* 추가로, `Navigation` component에 알맞은 icon과 `usePathname` 을 사용하던 로직을 `useSelectedLayoutSegment` 를 사용하도록 리팩토링한다.

### 📌 ToDo

- [X] Tailwind Prettier Plugin 설치 및 세팅
- [X] 불필요한 tailwind 클래스명 삭제
- [X] `flex-grow` 관련 CSS를 정리
- [X] `Navigation` component icon 변경 및 로직 변경

### 💬 Others

* 리팩토링 그만해야되는데.. 🥲
