### ISSUE TITLE
Feat: deploy using docker and github action

### ISSUE THREAD

**Issue by Goonco** [swm-standard/phote-client#33]
### 🤔 Description

* Docker를 활용해 EC2에 프로젝트 빌드 파일을 배포하고 Github action을 통해 이를 자동화한다.

### 📌 ToDo

- [X] `Dockerfile` 구성
- [X] EC2 인스턴스 생성
- [X] EC2에 Docker 설치
- [X] `github-actions.yaml` 구성 및 secrets 추가

### 💬 Others

* 첫 배포 과연 얼마나 걸릴까..? 🤨
