### ISSUE TITLE
Design: publishing question search page and implement sub features

### ISSUE THREAD

**Issue by Goonco** [swm-standard/phote-client#43]
### 🤔 Description

* 문제 조회 페이지의 퍼블리싱을 진행한다.
* 기존에 구현된 검색 로직을 유지하며 추가적인 API 호출 구현 없이 퍼블리싱에 집중한다.
* 필요 시 storybook을 수정하여 다양한 형태의 UI를 확인한다.

### 📌 ToDo

- [X] 문제 조회 페이지 퍼블리싱
- [X] Storybook으로 전시된 문제 수별 UI 확인
- [X] 문제 생성 페이지와 연결

### 💬 Others

* 화이팅! 👊💪
