### ISSUE TITLE
Fix: fix errors

### ISSUE THREAD

**Issue by Goonco** [swm-standard/phote-client#69]
### 🤔 Description

* 현재 배포된 서비스의 크고 작은 오류를 확인하고 해결한다.

### 📌 ToDo

- [x] 로그인 버튼 중심 정렬
- [x] 에러 핸들링
- [x] 소셜 로그인 에러 해결
- [x] 로그아웃
- [x] 회원탈퇴
- [x] 테스트 글자 깨짐 (시험 점수)
- [x] 공유
- [x] 문제 변환 시 섹션 지정 안해도 변환

### 💬 Others

* Maybe comments or memo for future you or other teammates
