### ISSUE TITLE
Fix: bug fix

### ISSUE THREAD

**Issue by Goonco** [swm-standard/phote-client#74]
### 🤔 Description

잔 오류 및 기능 수정

### 📌 ToDo

- [x] 한글로 태그 생성 시, 태그 두개 생성 이슈
- [x] 공유 페이지 스타일링
- [x] 문제집 내 문제 개수 0개일 때 시험보기 오류
- [ ] 갑자기 문제 목록 안불러와짐 오류

### 💬 Others

* Maybe comments or memo for future you or other teammates
